ignore:
  - "**/Migrations/*.cs"
  - "**/Extensions/*.cs"
  - "**/ExceptionHandlers/*.cs"
  - "**/*DbContextModelSnapshot.cs"
  - "**/*.Designer.cs"
  - "**/StoreDbContext.cs"
  - "**/StoreDbContextSeeder.cs"
  - "**/IdentityServerDbContext.cs"
  - "**/IdentityServerDbContextSeeder.cs"
  - "**/obj/"
  - "**/bin/"
  - "**/Program.cs"
  - "**/AppOptions/*.cs"
  - "**/Commons/**/*.cs"
  - "**/*.cshtml"
  - "**/NashFridayStore.Domain/**"
  - "**/Auth/**"

  # Some specific endpoints not need for testings
  - "**/GetMyOrders/**"
  - "**/Dockerfile"
