ignore:
  - "**/Migrations/*.cs"
  - "**/Extensions/*.cs"
  - "**/ExceptionHandlers/*.cs"
  - "**/*DbContextModelSnapshot.cs"
  - "**/*.Designer.cs"
  - "**/StoreDbContext.cs"
  - "**/StoreDbContextSeeder.cs"
  - "**/IdentityServerDbContext.cs"
  - "**/IdentityServerDbContextSeeder.cs"
  - "**/obj/"
  - "**/bin/"
