services:
  # Store Database
  nashfridaystore-db-store:
    container_name: nashfridaystore-db-store
    image: mcr.microsoft.com/mssql/server:2025-latest
    restart: always
    ports:
      - 1433:1433
    volumes:
      - nashfridaystore-db-store-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
    env_file:
      - path: .secrets/nashfridaystore-db-store.env
        required: true
    networks:
      - nashfridaystore-network

  # Identity Server Database
  nashfridaystore-db-identityserver:
    container_name: nashfridaystore-db-identityserver
    image: mcr.microsoft.com/mssql/server:2025-latest
    restart: always
    ports:
      - 1434:1433
    volumes:
      - nashfridaystore-db-identityserver-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
    env_file:
      - path: .secrets/nashfridaystore-db-identityserver.env
        required: true
    networks:
      - nashfridaystore-network

  # Cart Redis
  # - using --appendonly to persist cart in memory even redis crashes
  nashfridaystore-redis-cart:
    container_name: nashfridaystore-redis-cart
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - nashfridaystore-redis-cart-data:/data
    env_file:
      - path: .secrets/nashfridaystore-redis-cart.env
        required: true
    networks:
      - nashfridaystore-network
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $${REDIS_PASSWORD} ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    command: >
      sh -c "redis-stack-server --requirepass $${REDIS_PASSWORD} --databases $${REDIS_DATABASES} --appendonly yes"

  # Redis Insight For Monitoring
  nashfridaystore-redisinsight:
    container_name: nashfridaystore-redisinsight
    image: redis/redisinsight:latest
    restart: always
    depends_on:
      nashfridaystore-redis-cart:
        condition: service_healthy
    ports:
      - "5540:5540"
    volumes:
      - nashfridaystore-redisinsight-data:/data
    networks:
      - nashfridaystore-network

  # Stripe CLI, listening webhook from Stripe
  nashfridaystore-stripe-cli:
    container_name: nashfridaystore-stripe-cli
    image: stripe/stripe-cli:latest
    restart: unless-stopped
    env_file:
      - path: .secrets/nashfridaystore-stripe-cli.env
        required: true
    command:
      - listen
      - --api-key
      - ${STRIPE_API_KEY}
      - --forward-to
      - https://host.docker.internal:7176/api/orders/webhook
      - --skip-verify

volumes:
  nashfridaystore-db-store-data:
  nashfridaystore-db-identityserver-data:
  nashfridaystore-redis-cart-data:
  nashfridaystore-redisinsight-data:


networks:
  nashfridaystore-network:
    driver: bridge
